### ISSUE TITLE
Add base64 decoding to Pub/Sub message conversion

### ISSUE THREAD

**Issue by grayside** [googleapis/google-cloudevents-nodejs#48]
## Expected Behavior

As part of message conversion, decode the message for the developer. If the message is further in JSON or other format beyond a simple string, I expect the developer to handle that.

## Actual Behavior

Message conversion is followed immediately by base64 decoding for any use case not limited to attributes.

The encoding is an uninteresting implementation detail of the message format.

**Comment by grant** [comment]
Thanks for the issue @grayside, 

I see some usefulness in automatically decoding the message for the developer, but I think this suggestion has some issues in it's design and expectations for developers:

- A developer may not want to have the message of their payload decoded. For example, they may send the message to a different service.
- This is a feature that is one-off for a specific data type. I don't see how it expands to other CloudEvent types.
- This would require this client to `JSON.parse` the data. That's not in scope for this library and may lead to unintended behavior.
- A user can easily shoot themselves in the foot if they try to base64 decode the message twice. We're going to have some samples that decode/encode and some that don't.
- decoding/encoding base64 is easy in JS. Just use `atob` or `btoa`. Any method that tries to make that simpler is going to be convoluted.

As such, I am opposed to handling certain CloudEvents in special ways. We can certainly provide examples like we currently do in our Pub/Sub, Run, Functions docs.

CC @jskeet to chime in if interested.

Will close, but can re-open if requested.

**Comment by jskeet** [comment]
This is the kind of thing where being able to augment the generated library can be useful. In C# we have a [partial class](https://github.com/googleapis/google-cloudevents-dotnet/blob/master/src/Google.Events.Protobuf/Cloud/PubSub/V1/PubsubMessageData.cs) to decode the binary data to text - the base64 decoding is done automatically in protobuf-land.

In terms of being a one-off, it would apply to any protobuf `bytes` field - I'd say it's pretty rare, but not entirely a one-off. It's not like this is a string field that has just been documented as containing base64 data.

I'm happy to defer to @grant's conclusion here - just wanted to give a bit of extra context.

(As an aside, in [my most recent foray into JavaScript](https://codeblog.jonskeet.uk/2020/07/12/v-drum-explorer-blazor-and-the-web-midi-api/), base64-decoding was actually the most frustrating aspect, but I suspect that's specific to what I was trying to do.)
