### ISSUE TITLE
Enriched in-line comments for generated files

### ISSUE THREAD

**Issue by grayside** [googleapis/google-cloudevents-nodejs#51]
## Expected Behavior

* Comments at the top of the file clarify it is generated and point to instructions for how to re-generate. This empowers contributors.
* Comments at the top of the file reference the schema URL used to generate it. This allows easy cross-reference to know if something is out of sync.
* Comments for individual data types deep link to relevant product documentation to get more context.

## Actual Behavior

* Need to understand the library "top down" to realize it's generated.
* Need to track down code in multiple repositories to verify the schema source of a given version of the library
* No path to further context in reading about data types via IDE tooltips.

**Comment by grant** [comment]
Thanks for the issue.

I think we can include a `README.md` comment in the repo the source code is generated like we do with almost all client libraries. Here's an example: https://github.com/googleapis/google-api-nodejs-client#google-apis

## Detailed Replies

> * Comments at the top of the file clarify it is generated and point to instructions for how to re-generate. This empowers contributors.

- I've looked at other generated libraries.
  - The Google APIs node clients do not include a comment per source that the file was gen'd. I think one comment per repo would stop confusion from users.

> * Comments at the top of the file reference the schema URL used to generate it. This allows easy cross-reference to know if something is out of sync.

- Things should not be out of sync as the schema should not change in a breaking way with our versioning. **A particular release** of this library and **npm version** will determine the release date if someone wants to look that up.
  - It's a good point. We should add a SHA or actual tags in https://github.com/googleapis/google-cloudevents to make it easier to determine at which point this library was generated.
- The Google API node clients do not include a reference to the schema/discovery.

I think we can just state that this repo is generated from the JSON Schema source and use release-please's git tagging system.

> * Comments for individual data types deep link to relevant product documentation to get more context.

- I don't know if we should deep link into the product docs, but a shallow link to the general product page would be okay. That's more of an issue with the schema than this client.

**Comment by grant** [comment]
Hey Adam, looking at how other client libraries operate, and reasons of simplicity, I'm inclined to close this issue.

I would imagine a developer goes to GitHub if they have an issue with this repo.

In API clients, we do not include the schema (discovery document, instructions on how to generate the client (usually in CONTRIBUTING), or product docs (maybe that should be in the schema))

For example, Node `cloudrun:v1` API:

https://github.com/googleapis/google-api-nodejs-client/blob/master/src/apis/run/v1.ts

---

Perhaps schedule a meeting to talk about this? I'm going to close, but feel free to re-open with replies to this or the above comment.
